name: Release to GitHub and NPM
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'next'
      - 'main'
env:
  HUSKY: 0
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ksentak01/cpp-node-container:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Set file permissions
        run: |
          chmod -R 755 ./
          chown -R $(id -u):$(id -g) ./

      - name: Generate OpenRpc
        run: |
          npm run dist

      - name: Get version from package.json
        run: |
          RELEASE_VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "build_cpp_source=true" >> $GITHUB_ENV

      - name: Set cpp build source Condition
        if: steps.check_build.outputs.files_exists == 'false' || (github.ref_name == 'main' && github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch')
        run: echo "build_cpp_source=false" >> $GITHUB_ENV

      - name: Generate native sdk source
        if: env.build_cpp_source == 'true'
        run: |
          .github/workflows/utils.sh generateSource

      - name: Clone and Install Thunder
        if: env.build_cpp_source == 'true'
        id: install_thunder
        run: |
          .github/workflows/utils.sh cloneAndInstallThunder

      - name: Build Core SDK CPP
        if: env.build_cpp_source == 'true'
        id: build_core_cpp
        run: |
          .github/workflows/utils.sh buildCoreCPPSDK 1.3.0-next.1

      - name: Build Manage SDK CPP
        if: env.build_cpp_source == 'true'
        id: build_manage_cpp
        run: |
          .github/workflows/utils.sh buildManageCPPSDK 1.3.0-next.1

      # - name: Build Discovery SDK CPP
      #   if: env.build_cpp_source == 'true'
      #   id: build_discovery_cpp
      #   run: |
      #     .github/workflows/utils.sh buildDiscoveryCPPSDK $RELEASE_VERSION
